# Generated by Django 4.2.5 on 2023-09-25 09:09

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                (
                    "jobtype",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("secondary", "Secondary"),
                            ("internship", "Internship"),
                        ],
                        default="permanent",
                        max_length=100,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "Phd"),
                        ],
                        default="bachelor",
                        max_length=100,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("Bussiness", "Bussiness"),
                            ("Banking", "Banking"),
                            ("Information Technology", "It"),
                            ("Education/traning", "Education"),
                            ("Telecommunication", "Telecommunication"),
                            ("Others", "Others"),
                        ],
                        default="Bussiness",
                        max_length=100,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("NO_Experience", "No Experience"),
                            ("One_Year", "One Year"),
                            ("Two_Years", "Two Years"),
                            ("Three_Years_Plus", "Three Years Plus"),
                        ],
                        default="NO_Experience",
                        max_length=100,
                    ),
                ),
                (
                    "salary",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                ("position", models.IntegerField(default=1)),
                ("company", models.CharField(max_length=100, null=True)),
                ("lastdate", models.DateTimeField(default=app.models.return_date_time)),
                ("creatAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
